### ISSUE TITLE
spelling mistakes in meta files

### ISSUE THREAD

**Issue by itaibaz** [opencomputeproject/SAI#1319] opened 2021-09-30 01:01 UTC
@kcudnik 
There are few clear spelling mistakes in meta files

2021-09-30 00:58:53,243 - spellchecktoolbox - INFO - Checking misspellings in file: mlnx_sai/src/meta/saimetadatautils.c for revision: b76ebaa7ef05fcbfd0488e467d8584da07c3285e 
2021-09-30 00:58:53,320 - spellchecktoolbox - ERROR - Misspelled word: condtion --> line: 460 : /* attr list can be NULL, condtion could be based on default value */
2021-09-30 00:58:53,320 - spellchecktoolbox - ERROR - Misspelled word: condtion --> line: 489 : /* attr list can be NULL, condtion could be based on default value */

2021-09-30 00:58:53,408 - spellchecktoolbox - INFO - Checking misspellings in file: mlnx_sai/src/meta/saisanitycheck.c for revision: b76ebaa7ef05fcbfd0488e467d8584da07c3285e 
2021-09-30 00:58:53,603 - spellchecktoolbox - ERROR - Misspelled word: objec --> line: 5368 : * will have no more than 255 objec types on SAI right now.

Can we run aspell on all of them, as part of commit checker ?

**Comment by kcudnik** [comment] 2021-09-30 09:05
this issue is duplicate of the https://github.com/opencomputeproject/SAI/issues/1225 which you also opened, and i still didn't had time to add spell checker, since i treated this as low priority, let me sit on this since this should be easy to implement

**Comment by kcudnik** [comment] 2021-09-30 11:49
Fix https://github.com/opencomputeproject/SAI/pull/1320

**Closed** 2021-10-01 08:07 UTC
